apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

image: node:latest

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://node:latest
        shell: sh
        run: |
          npm i
          npm run dev
